/* ============================================================
   Smart Agents — core datasets
   ------------------------------------------------------------
   `agents`, `detections`, `quickThen`, `agentDetId` and
   `detLibrary` are transcribed VERBATIM from the component
   script in `Smart Agents v2.dc.html`.
   `templates` is transcribed from `Smart Agents.dc.html` (v1),
   which retained the array the v2 file truncated; the final
   entry (`t-delinq`) was cut off in both files and is
   reconstructed from `detLibrary`/`agents` — see NOTES.md.
   ============================================================ */
(function (SA) {
  'use strict';

  SA.agents = [
    { kind: 'Agent', id: 'movein', name: 'Move-In Charge Integrity', type: 'Data health', mode: 'builder', trigger: 'Nightly', last: 'Today 2:04am', state: '9 open findings', enabled: true, findings: 9, orion: true },
    { kind: 'Agent', id: 'w9', name: 'Vendor W-9 Compliance', type: 'Data health', mode: 'quick', trigger: 'Weekly', last: 'Mon 5:01am', state: '3 open findings', enabled: true, findings: 3, orion: true },
    { kind: 'Automation', id: 'wo', name: 'Work Order SLA Breach', type: 'Notification', mode: 'rule', trigger: 'A work order passes its SLA', last: 'Today 11:40am', state: '2 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the maintenance supervisor and the assigned technician' },
    { kind: 'Automation', id: 'insurance', name: 'Resident Insurance Lapse', type: 'Notification', mode: 'rule', trigger: 'Policy end date passes · Daily', last: 'Today 8:00am', state: '11 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the resident and notify the property manager' },
    { kind: 'Agent', id: 'residentdata', name: 'Missing Resident Data', type: 'Data health', mode: 'quick', trigger: 'Weekly', last: 'Mon 4:31am', state: '12 open findings', enabled: true, findings: 12, orion: true },
    { kind: 'Agent', id: 'credit', name: 'Credit Approval', type: 'Workflow', mode: 'builder', trigger: 'A credit is added to a tenant ledger', last: 'Today 10:04am', state: '7 decisions today', enabled: true, findings: 0, orion: true },
    { kind: 'Agent', id: 'bill', name: 'Bill Approval', type: 'Workflow', mode: 'builder', trigger: 'An invoice is received', last: 'Today 11:26am', state: '19 invoices today', enabled: true, findings: 0, orion: true },
    { kind: 'Agent', id: 'prospect', name: 'Prospect Follow-Up', type: 'Workflow', mode: 'builder', trigger: 'Daily', last: 'Today 7:01am', state: '23 touches today', enabled: true, findings: 0, orion: true },
    { kind: 'Automation', id: 'n-leaseexp', name: 'Lease Expiring', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · Lease end date approaches · Daily', last: 'Today 7:00am', setups: 3, defaultRecipient: 'Tenant', state: '3 setups · 86 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the resident and notify the property manager' },
    { kind: 'Automation', id: 'n-renewal', name: 'Renewal Offer Sent', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A renewal offer is sent', last: 'Today 9:14am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 41 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the renewal offer to the resident' },
    { kind: 'Automation', id: 'n-renewalstatus', name: 'Renewal Offer Status Updated', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A renewal offer status changes', last: 'Today 9:41am', setups: 3, defaultRecipient: 'Property Manager', state: '3 setups · 18 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the property manager of the new status' },
    { kind: 'Automation', id: 'n-renewalaging', name: 'Renewal Offer Aging', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A renewal offer waits for a response · Daily', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the resident that the offer is waiting' },
    { kind: 'Automation', id: 'n-movein', name: 'Move-In Confirmation', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A lease is signed', last: 'Yesterday 3:41pm', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 9 sent this month', enabled: true, findings: 0, orion: false, action: 'Email move-in details and the checklist to the resident' },
    { kind: 'Automation', id: 'n-welcome', name: 'Welcome Packet', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · The move-in date arrives', last: 'Aug 27, 8:00am', setups: 1, defaultRecipient: 'Tenant', state: '1 setups · 9 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the welcome packet to the new resident' },
    { kind: 'Automation', id: 'n-ntv', name: 'Notice to Vacate Received', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A notice to vacate is recorded', last: 'Aug 26, 2:12pm', setups: 3, defaultRecipient: 'Tenant', state: '3 setups · 6 sent this month', enabled: true, findings: 0, orion: false, action: 'Confirm receipt to the resident and notify the property manager' },
    { kind: 'Automation', id: 'n-brokenlease', name: 'New Move-In to a Unit with a Broken Lease', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A move-in is recorded on a unit with a broken lease', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the property manager to reconcile the unit' },
    { kind: 'Automation', id: 'n-survey', name: 'Survey (Poll) Closing', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A survey approaches its close date', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind residents to respond before the survey closes' },
    { kind: 'Automation', id: 'n-surveyresp', name: 'Survey Response Received', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A resident submits a survey response', last: 'Today 9:02am', setups: 1, defaultRecipient: 'Jonathan Cameron', state: '1 setups · 22 sent this month', enabled: true, findings: 0, orion: false, action: 'Forward the response to the survey owner' },
    { kind: 'Automation', id: 'n-surveylink', name: 'Survey Link Expiring', notifGroup: 'Leasing & Residents', subType: 'Leasing & Residents', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A survey link approaches expiry · Daily', last: 'Today 6:20am', setups: 1, defaultRecipient: 'Primary Contact', state: '1 setups · 8 sent this month', enabled: true, findings: 0, orion: false, action: 'Remind the resident before the link expires' },
    { kind: 'Automation', id: 'n-guestcard', name: 'Prospect Guest Card Submitted', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A prospect submits a guest card', last: 'Today 10:52am', setups: 1, defaultRecipient: 'Leasing Agent', state: '1 setups · 34 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the leasing agent with the prospect details' },
    { kind: 'Automation', id: 'n-ownerguestcard', name: 'Owner Prospect Guest Card Submitted', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An owner prospect submits a guest card', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the leasing agent with the owner prospect details' },
    { kind: 'Automation', id: 'n-notcontacted', name: 'Prospect Not Contacted', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A prospect goes uncontacted · Daily', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the leasing agent of prospects with no logged contact' },
    { kind: 'Automation', id: 'n-ownernotcontacted', name: 'Owner Prospect Not Contacted', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner prospect goes uncontacted · Daily', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the leasing agent of owner prospects with no contact' },
    { kind: 'Automation', id: 'n-prospectstage', name: 'Prospect Stage Changed', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A prospect moves to a new stage', last: 'Today 10:44am', setups: 1, defaultRecipient: 'Primary Contact', state: '1 setups · 57 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the leasing agent of the stage change' },
    { kind: 'Automation', id: 'n-rentquote', name: 'Rent Quote Expiring', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A rent quote approaches expiry · Daily', last: 'Today 6:30am', setups: 1, defaultRecipient: 'Primary Contact', state: '1 setups · 6 sent this month', enabled: true, findings: 0, orion: false, action: 'Warn the prospect that the quoted rate expires' },
    { kind: 'Automation', id: 'n-webchat', name: 'Web Chat Offline Message', notifGroup: 'Prospects & Leads', subType: 'Prospects & Leads', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A web chat message arrives while offline', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Forward the chat message to the leasing inbox' },
    { kind: 'Automation', id: 'latefee', name: 'Late Fee Posting', notifGroup: 'Financial', subType: 'Financial', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A late fee posts', last: 'Today 6:30am', setups: 2, defaultRecipient: 'Primary Contact', state: '2 setups · 18 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the resident with the fee and the new balance' },
    { kind: 'Automation', id: 'receipt', name: 'Payment Received', notifGroup: 'Financial', subType: 'Financial', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A payment posts', last: 'Today 11:52am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 212 sent this month', enabled: true, findings: 0, orion: false, action: 'Email a receipt to the paying resident' },
    { kind: 'Automation', id: 'n-nsf', name: 'Payment Returned (NSF)', notifGroup: 'Financial', subType: 'Financial', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A payment is returned', last: 'Aug 25, 7:02am', setups: 3, defaultRecipient: 'Tenant', state: '3 setups · 4 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the resident and the property manager, and flag the ledger' },
    { kind: 'Automation', id: 'n-stmt', name: 'Statement Available', notifGroup: 'Financial', subType: 'Financial', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A statement is generated', last: 'Aug 2, 4:10am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 398 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the statement link to the resident' },
    { kind: 'Automation', id: 'n-autopay', name: 'Autopay Draft Reminder', notifGroup: 'Financial', subType: 'Financial', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · 3 days before the draft', last: 'Aug 31, 6:00am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 286 sent this month', enabled: true, findings: 0, orion: false, action: 'Remind the resident of the upcoming draft amount' },
    { kind: 'Automation', id: 'n-issuesched', name: 'Issue Scheduled', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A service issue is scheduled', last: 'Today 10:22am', setups: 3, defaultRecipient: 'Tenant', state: '3 setups · 64 sent this month', enabled: true, findings: 0, orion: false, action: 'Tell the resident and the assigned user the scheduled date' },
    { kind: 'Automation', id: 'wotech', name: 'Work Order Assigned', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A work order is assigned', last: 'Today 10:18am', setups: 2, defaultRecipient: 'Assigned User', state: '2 setups · 64 sent this month', enabled: true, findings: 0, orion: false, action: 'Text the assigned technician with the unit and problem' },
    { kind: 'Automation', id: 'n-wodone', name: 'Work Order Completed', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A work order is closed', last: 'Today 9:40am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 58 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the resident a completion summary and survey link' },
    { kind: 'Automation', id: 'wo', name: 'Work Order Past SLA', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A work order passes its SLA', last: 'Today 11:40am', setups: 2, defaultRecipient: 'Assigned User', state: '2 setups · 2 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the maintenance supervisor and the assigned technician' },
    { kind: 'Automation', id: 'n-inspect', name: 'Inspection Due', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An inspection comes due', last: 'Aug 20, 6:00am', setups: 2, defaultRecipient: 'Property Manager', state: '2 setups · 5 sent this month', enabled: true, findings: 0, orion: false, action: 'Notify the property manager and the resident' },
    { kind: 'Automation', id: 'n-inspectclosed', name: 'Inspection Closed', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An inspection is closed', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Send the completed inspection summary' },
    { kind: 'Automation', id: 'n-selfinspect', name: 'Tenant Self Inspection Awaiting Review', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A resident submits a self inspection', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Ask the property manager to review the submission' },
    { kind: 'Automation', id: 'n-mgmtinspect', name: 'Management Inspection Scheduled', notifGroup: 'Maintenance & Inspections', subType: 'Maintenance & Inspections', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A management inspection is scheduled', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the resident when the inspection will happen' },
    { kind: 'Automation', id: 'n-docsigned', name: 'Document Signed', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A signable document is signed', last: '—', setups: 0, defaultRecipient: 'Signer', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Confirm the completed signature to all parties' },
    { kind: 'Automation', id: 'n-signaging', name: 'Signable Document Aging', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · Any signable document waits unsigned · Daily', last: '—', setups: 0, defaultRecipient: 'Signer', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the signer that the document is still waiting' },
    { kind: 'Automation', id: 'n-tenantsignaging', name: 'Tenant Signable Document Aging', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A tenant document waits unsigned · Daily', last: 'Today 6:00am', setups: 1, defaultRecipient: 'Signer', state: '1 setups · 12 sent this month', enabled: true, findings: 0, orion: false, action: 'Remind the signer that the document is still waiting' },
    { kind: 'Automation', id: 'n-prospectsignaging', name: 'Prospect Signable Document Aging', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A prospect document waits unsigned · Daily', last: 'Today 6:00am', setups: 1, defaultRecipient: 'Signer', state: '1 setups · 7 sent this month', enabled: true, findings: 0, orion: false, action: 'Remind the prospect that the document is still waiting' },
    { kind: 'Automation', id: 'n-ownersignaging', name: 'Owner Signable Document Aging', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner document waits unsigned · Daily', last: '—', setups: 0, defaultRecipient: 'Owner', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the owner that the document is still waiting' },
    { kind: 'Automation', id: 'n-ownerprospectsignaging', name: 'Owner Prospect Signable Document Aging', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner prospect document waits unsigned · Daily', last: '—', setups: 0, defaultRecipient: 'Owner Prospect', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the owner prospect that the document is still waiting' },
    { kind: 'Automation', id: 'n-landlordsign', name: 'Signable Document Waiting for Landlord Signature', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A document waits on the landlord · Daily', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the property manager a document is waiting on them' },
    { kind: 'Automation', id: 'n-bmsigned', name: 'Blue Moon eSignature Document Signed', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A Blue Moon document is signed', last: 'Today 8:50am', setups: 1, defaultRecipient: 'Gayatri Harikrishnan', state: '1 setups · 14 sent this month', enabled: true, findings: 0, orion: false, action: 'Confirm the signature to the leasing team' },
    { kind: 'Automation', id: 'n-bmcomplete', name: 'Blue Moon eSignature Document Completed', notifGroup: 'Documents & Signatures', subType: 'Documents & Signatures', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A Blue Moon document completes', last: '—', setups: 0, defaultRecipient: 'Signer', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Send the completed document to all parties' },
    { kind: 'Automation', id: 'n-ownerestaging', name: 'Owner Estimate Aging', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner estimate waits for a decision · Daily', last: 'Today 6:10am', setups: 1, defaultRecipient: 'Owner', state: '1 setups · 3 sent this month', enabled: true, findings: 0, orion: false, action: 'Remind the owner that the estimate is waiting' },
    { kind: 'Automation', id: 'n-ownerestexp', name: 'Owner Estimate Expiring', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner estimate approaches expiry', last: '—', setups: 0, defaultRecipient: 'Owner', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Warn the owner that the estimate is about to expire' },
    { kind: 'Automation', id: 'n-tenantestaging', name: 'Tenant Estimate Aging', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A tenant estimate waits for a decision · Daily', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the resident that the estimate is waiting' },
    { kind: 'Automation', id: 'n-tenantestexp', name: 'Tenant Estimate Expiring', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A tenant estimate approaches expiry', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Warn the resident that the estimate is about to expire' },
    { kind: 'Automation', id: 'n-estapproved', name: 'Estimate Approved via OWA', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An estimate is approved in owner web access', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the property manager that work is approved' },
    { kind: 'Automation', id: 'n-estrejected', name: 'Estimate Rejected via OWA', notifGroup: 'Estimates', subType: 'Estimates', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An estimate is rejected in owner web access', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the property manager that work was rejected' },
    { kind: 'Automation', id: 'n-amenapproval', name: 'Amenity Reservation Approval Needed', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A reservation needs approval', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Ask the property manager to approve the reservation' },
    { kind: 'Automation', id: 'n-amenupcoming', name: 'Amenity Reservation Upcoming', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A reservation date approaches', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the resident of the upcoming reservation' },
    { kind: 'Automation', id: 'n-amendenied', name: 'Amenity Reservation Denied', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A reservation is denied', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the resident the reservation was denied' },
    { kind: 'Automation', id: 'n-amencanceled', name: 'Amenity Reservation Canceled', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A reservation is canceled', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Confirm the cancellation to the resident' },
    { kind: 'Automation', id: 'n-str', name: 'STR Reservation Added', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A short-term reservation is added', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the property manager of the new reservation' },
    { kind: 'Automation', id: 'n-strarrival', name: 'STR Reservation Upcoming Arrival', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An arrival date approaches · Daily', last: 'Today 6:40am', setups: 2, defaultRecipient: 'Guest', state: '2 setups · 17 sent this month', enabled: true, findings: 0, orion: false, action: 'Send arrival instructions to the guest' },
    { kind: 'Automation', id: 'n-strfinalpay', name: 'STR Reservation Final Payment Made', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A final payment is made', last: '—', setups: 0, defaultRecipient: 'Guest', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Confirm the final payment to the guest' },
    { kind: 'Automation', id: 'n-strpayremind', name: 'STR Reservation Payment Reminder', notifGroup: 'Amenities & Reservations', subType: 'Amenities & Reservations', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A reservation payment comes due · Daily', last: '—', setups: 0, defaultRecipient: 'Guest', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the guest of the payment due' },
    { kind: 'Automation', id: 'n-archsubmitted', name: 'Architectural Request Submitted', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An architectural request is submitted', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the property manager of the new request' },
    { kind: 'Automation', id: 'n-archaging', name: 'Architectural Request Aging', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A request waits for a decision · Daily', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the board that a request is waiting' },
    { kind: 'Automation', id: 'n-archstatus', name: 'Architectural Request — Status Changed', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An architectural request status changes', last: 'Today 8:22am', setups: 4, defaultRecipient: 'Submitting Tenant', state: '4 setups · 11 sent this month', enabled: true, findings: 0, orion: false, action: 'Tell the submitting resident and the board the new status' },
    { kind: 'Automation', id: 'n-archvoting', name: 'Architectural Request Voting Complete', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · Voting completes on a request', last: '—', setups: 0, defaultRecipient: 'Submitting Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the submitting resident the voting outcome' },
    { kind: 'Automation', id: 'n-archtwa', name: 'Architectural Request Updated via TWA', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A resident updates a request in tenant web access', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the board of the resident update' },
    { kind: 'Automation', id: 'n-archmsg', name: 'Architectural Request — New Message Received', notifGroup: 'Architectural Requests', subType: 'Architectural Requests', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A new message is posted on a request', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Forward the message to the board' },
    { kind: 'Automation', id: 'n-poassigned', name: 'Purchase Order Assigned', notifGroup: 'Purchasing & AP', subType: 'Purchasing & AP', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A purchase order is assigned', last: '—', setups: 0, defaultRecipient: 'Assigned User', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the assigned user of the purchase order' },
    { kind: 'Automation', id: 'n-poaging', name: 'Purchase Order Aging', notifGroup: 'Purchasing & AP', subType: 'Purchasing & AP', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A purchase order waits for approval · Daily', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Remind the approver that a purchase order is waiting' },
    { kind: 'Automation', id: 'n-w9', name: 'Vendor W-9 Missing', notifGroup: 'Purchasing & AP', subType: 'Purchasing & AP', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · A vendor passes the 1099 threshold', last: 'Aug 24, 5:02am', setups: 1, defaultRecipient: 'Vendor', state: '1 setups · 3 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the W-9 request to the vendor contact' },
    { kind: 'Automation', id: 'n-incomeverif', name: 'Income Verification Report Received', notifGroup: 'Applications & Screening', subType: 'Applications & Screening', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An income verification report arrives', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Notify the leasing agent that the report is ready' },
    { kind: 'Automation', id: 'n-incomelink', name: 'Request for New Income Verification Link', notifGroup: 'Applications & Screening', subType: 'Applications & Screening', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An applicant requests a new verification link', last: '—', setups: 0, defaultRecipient: 'Leasing Agent', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Send a new verification link to the applicant' },
    { kind: 'Automation', id: 'n-evictionaging', name: 'Eviction Stage Aging', notifGroup: 'Collections & Legal', subType: 'Collections & Legal', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An eviction sits in one stage · Daily', last: '—', setups: 0, defaultRecipient: 'Property Manager', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the property manager the case has not moved' },
    { kind: 'Automation', id: 'insurance', name: 'Renters Insurance Lapse', notifGroup: 'Compliance', subType: 'Compliance', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A policy end date passes · Daily', last: 'Today 8:00am', setups: 2, defaultRecipient: 'Tenant', state: '2 setups · 11 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the resident and notify the property manager' },
    { kind: 'Automation', id: 'n-violation', name: 'Violation Due', notifGroup: 'Compliance', subType: 'Compliance', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · A violation reaches its due date · Daily', last: '—', setups: 0, defaultRecipient: 'Tenant', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Tell the resident the violation is due' },
    { kind: 'Automation', id: 'n-ownerstmt', name: 'Owner Statement Ready', notifGroup: 'Owner & Reporting', subType: 'Owner & Reporting', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · An owner statement is generated', last: 'Aug 2, 5:00am', setups: 1, defaultRecipient: 'Owner', state: '1 setups · 3 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the statement to the owner contact' },
    { kind: 'Automation', id: 'n-ownersum', name: 'Monthly Owner Summary', notifGroup: 'Owner & Reporting', subType: 'Owner & Reporting', type: 'Notification', mode: 'rule', trigKind: 'Schedule', trigger: 'Schedule · Monthly', last: 'Aug 3, 6:00am', setups: 1, defaultRecipient: 'Owner', state: '1 setups · 3 sent this month', enabled: true, findings: 0, orion: false, action: 'Email the portfolio summary to each owner' },
    { kind: 'Automation', id: 'n-ownerpaid', name: 'Owner Paid via Pay Owners', notifGroup: 'Owner & Reporting', subType: 'Owner & Reporting', type: 'Notification', mode: 'rule', trigKind: 'Event', trigger: 'Event · An owner payment is issued', last: '—', setups: 0, defaultRecipient: 'Owner', state: 'Not configured', enabled: false, findings: 0, orion: false, action: 'Confirm the payment and amount to the owner' },
    { kind: 'Automation', id: 'sch-rc-res', name: 'Residential Rent — 1st', schedType: 'Recurring Charges', subType: 'Recurring Charges', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 1, 2:10am', state: '412 charges posted', enabled: true, findings: 0, orion: false, action: 'Post recurring charges for every active residential lease' },
    { kind: 'Automation', id: 'sch-rc-com', name: 'Commercial CAM — 1st', schedType: 'Recurring Charges', subType: 'Recurring Charges', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 1, 2:14am', state: '38 charges posted', enabled: true, findings: 0, orion: false, action: 'Post CAM and base rent for commercial leases' },
    { kind: 'Automation', id: 'sch-rc-stu', name: 'Student Housing — Semi-monthly', schedType: 'Recurring Charges', subType: 'Recurring Charges', type: 'Schedule', mode: 'rule', trigger: 'Semi-monthly', last: 'Aug 15, 2:16am', state: '96 charges posted', enabled: false, findings: 0, orion: false, action: 'Post semi-monthly charges for student leases' },
    { kind: 'Automation', id: 'sch-lf-res', name: 'Residential Late Fee — Day 6', schedType: 'Late Fee', subType: 'Late Fee', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 6, 2:12am', state: '18 fees posted', enabled: true, findings: 0, orion: false, action: 'Post late fees against residential balances past grace' },
    { kind: 'Automation', id: 'sch-lf-com', name: 'Commercial Late Fee — Day 11', schedType: 'Late Fee', subType: 'Late Fee', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 11, 2:12am', state: '3 fees posted', enabled: true, findings: 0, orion: false, action: 'Post late fees against commercial balances past grace' },
    { kind: 'Automation', id: 'sch-mgmt', name: 'Owner Management Fee', schedType: 'Management Fee', subType: 'Management Fee', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 1, 2:20am', state: '3 fees posted', enabled: true, findings: 0, orion: false, action: 'Post the management fee for each owner' },
    { kind: 'Automation', id: 'sch-gpr', name: 'GPR Refresh', schedType: 'GPR', subType: 'GPR', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 1, 2:24am', state: '3 properties updated', enabled: true, findings: 0, orion: false, action: 'Recalculate gross potential rent for each property' },
    { kind: 'Automation', id: 'sch-epay', name: 'Resident ePay Drafts — Day 3', schedType: 'Recurring ePay', subType: 'Recurring ePay', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 3, 5:00am', state: '286 payments drafted', enabled: true, findings: 0, orion: false, action: 'Draft scheduled resident ePay payments' },
    { kind: 'Automation', id: 'sch-util', name: 'Utility Billing — Day 8', schedType: 'Utility', subType: 'Utility', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 8, 3:00am', state: '141 charges posted', enabled: true, findings: 0, orion: false, action: 'Post utility charges from the current billing file' },
    { kind: 'Automation', id: 'sch-rubs', name: 'RUBS Allocation — Day 9', schedType: 'Utility', subType: 'Utility', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 9, 3:10am', state: '204 charges posted', enabled: true, findings: 0, orion: false, action: 'Allocate RUBS charges across occupied units' },
    { kind: 'Automation', id: 'sch-ar', name: 'Late Notice Series', schedType: 'AR', subType: 'AR', type: 'Schedule', mode: 'rule', arSteps: 4, trigger: 'Due date + offsets · Daily', last: 'Today 6:00am', state: '4 steps · 128 sent this month', enabled: true, findings: 0, orion: false, action: 'Send the dunning sequence to residents carrying a balance' },
    { kind: 'Automation', id: 'sch-ar-bal', name: 'Outstanding Balance Series', schedType: 'AR', subType: 'AR', type: 'Schedule', mode: 'rule', arSteps: 2, trigger: 'Due date + offsets · Daily', last: 'Today 6:00am', state: '2 steps · 46 sent this month', enabled: true, findings: 0, orion: false, action: 'Send the dunning sequence to residents carrying a balance' },
    { kind: 'Automation', id: 'sch-ar-com', name: 'Commercial Balance Series', schedType: 'AR', subType: 'AR', type: 'Schedule', mode: 'rule', arSteps: 3, trigger: 'Due date + offsets · Daily', last: 'Today 6:00am', state: '3 steps · 9 sent this month', enabled: false, findings: 0, orion: false, action: 'Send the dunning sequence to residents carrying a balance' },
    { kind: 'Automation', id: 'sch-stmt', name: 'Monthly Statements — Day 2', schedType: 'Tenant Statement', subType: 'Tenant Statement', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 2, 4:00am', state: '398 statements sent', enabled: true, findings: 0, orion: false, action: 'Generate and send tenant statements' },
    { kind: 'Automation', id: 'sch-loans', name: 'Loans Billing — Day 1', schedType: 'Loans Receivable', subType: 'Loans Receivable', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 1, 2:30am', state: '12 loans billed', enabled: true, findings: 0, orion: false, action: 'Bill scheduled loans receivable' },
    { kind: 'Automation', id: 'sch-loanslate', name: 'Loans Late Fee — Day 6', schedType: 'Loans Receivable Late Fee', subType: 'Loans Receivable Late Fee', type: 'Schedule', mode: 'rule', trigger: 'Monthly', last: 'Aug 6, 2:34am', state: '2 fees posted', enabled: false, findings: 0, orion: false, action: 'Post late fees on past-due loans receivable' }
  ];

  /* `agents` contains two intentional id collisions carried over from the
     design source (`wo` and `insurance` each appear once as a legacy
     automation and once inside the notification catalogue). Routing keys off
     `key`, assigned here, so opening a row always opens that exact row. */
  SA.agents.forEach(function (a, i) { a.key = a.id + '#' + i; });

  SA.detections = {
    movein: {
      text: 'A resident moved in within the last 30 days but has no active recurring charges on the lease.',
      window: 'Move-in date: last 30 days',
      checks: ['Leases with a move-in date in the last 30 days', 'Lease status is active', 'No active recurring charge on the lease as of today', 'Excludes employee and model units'],
      result: 'Found 9 matching records'
    },
    delinq: {
      text: 'Residents whose payment history suggests another written reminder will not produce a payment.',
      window: 'Ledger history: last 24 months',
      checks: ['Balance is past the grace period', 'Payment timeliness over the last 24 months', 'Reminders already sent and whether they were answered', 'Broken payment arrangements and NSF events'],
      result: 'Found 23 matching records'
    },
    leaseexp: {
      text: 'A lease expires within 75 days with no renewal offer sent and no notice to vacate on file',
      window: 'Lease end date: next 75 days',
      checks: ['Lease end date is within 75 days', 'No renewal offer record exists on the lease', 'No notice to vacate on file', 'Lease status is active'],
      result: 'Found 14 matching records'
    },
    w9: {
      text: 'A vendor has received over $600 in payments this year and has no W-9 on file',
      window: 'Payments: current tax year',
      checks: ['Vendor payments this tax year exceed $600.00', 'No W-9 document attached to the vendor record', 'Vendor is active', 'Excludes vendors flagged as corporate exempt'],
      result: 'Found 3 matching records'
    },
    generic: {
      text: 'Records that look wrong, incomplete, or inconsistent against the signed agreement.',
      window: 'Last 30 days',
      checks: ['Record is active', 'Required fields are present and internally consistent', 'Values agree with the signed agreement', 'Excludes records dismissed by a human'],
      result: 'Found 5 matching records'
    }
  };

  SA.quickThen = { leaseexp: 'Notify the property manager', w9: 'Create a task for the AP manager' };

  SA.agentDetId = {
    leaseexp: 'lease-exp', w9: 'w9', movein: 'movein-charges', delinq: 'reminder-futility',
    credit: 'credit-request', bill: 'bill-pattern', prospect: 'prospect-cold',
    latefeegap: 'late-fee-missing', residentdata: 'missing-resident-data',
    credits: 'unusual-credits', deletes: 'unusual-deletes'
  };

  SA.detLibrary = [
    { id: 'lease-exp', group: 'Leasing', name: 'Lease expiring with no renewal activity', result: 'Found 14 matching records',
      seg: ['A lease expires within', { p: 'days', w: '64px' }, 'days with no renewal offer sent and no notice to vacate on file'],
      params: { days: '75' },
      checks: ['Lease end date is within {days} days', 'No renewal offer record exists on the lease', 'No notice to vacate on file', 'Lease status is active'] },
    { id: 'ntv-inspection', group: 'Leasing', name: 'Notice to vacate with no move-out inspection', result: 'Found 6 matching records',
      seg: ['A notice to vacate is on file with no move-out inspection scheduled within', { p: 'days', w: '56px' }, 'days of the move-out date'],
      params: { days: '7' },
      checks: ['Notice to vacate is on file', 'Move-out date is in the future', 'No inspection scheduled within {days} days of move-out'] },
    { id: 'movein-charges', group: 'Billing', name: 'Charges that do not match the lease', result: 'Found 12 matching records',
      seg: ['A lease is not being billed what it should be — no recurring charge after move-in within the last', { p: 'days', w: '64px' }, 'days, a charge below the signed rent, or rent more than', { p: 'gap', w: '84px' }, 'under market'],
      params: { days: '30', gap: '$100.00' },
      checks: ['Lease status is active', 'Excludes employee and model units'],
      any: ['Moved in within the last {days} days with no active recurring charge', 'Active recurring charge is below the rent on the signed lease', 'Rent is more than {gap} under the unit market rent at renewal'] },
    { id: 'rent-mismatch', group: 'Billing', name: 'Recurring charge does not match lease rent', result: 'Found 4 matching records',
      seg: ['A recurring rent charge differs from the signed lease rent by more than', { p: 'amount', w: '90px' }, 'per month'],
      params: { amount: '$25.00' },
      checks: ['Lease status is active', 'An active recurring rent charge exists on the lease', 'Charge amount differs from lease rent by more than {amount}'] },
    { id: 'concession', group: 'Billing', name: 'Concession active with no end date', result: 'Found 2 matching records',
      seg: ['A concession is active on a lease with no end date recorded'], params: {},
      checks: ['Concession charge is active', 'No end date recorded on the concession', 'Lease status is active'] },
    { kind: 'Agent', id: 'w9', group: 'Accounts payable', name: 'Vendor paid over threshold with no W-9', result: 'Found 3 matching records',
      seg: ['A vendor has received over', { p: 'amount', w: '90px' }, 'in payments this year and has no W-9 on file'],
      params: { amount: '$600' },
      checks: ['Vendor payments this tax year exceed {amount}', 'No W-9 document attached to the vendor record', 'Vendor is active', 'Excludes vendors flagged as corporate exempt'] },
    { id: 'dup-vendor', group: 'Accounts payable', name: 'Possible duplicate vendor', result: 'Found 3 matching records',
      seg: ['Two vendor records share a tax ID, bank account, or remit-to address'], params: {},
      checks: ['Vendor is active'],
      any: ['Tax ID matches another active vendor', 'Bank account matches another active vendor', 'Remit-to address matches another active vendor'] },
    { id: 'reminder-futility', group: 'Collections', name: 'Written reminder unlikely to produce payment', result: 'Found 23 matching records',
      seg: ['A past-due resident has', { p: 'nsf', w: '48px' }, 'or more NSF events in the last', { p: 'months', w: '48px' }, 'months, or a broken payment arrangement, and', { p: 'reminders', w: '48px' }, 'unanswered reminders'],
      params: { nsf: '2', months: '3', reminders: '2' },
      checks: ['Balance is past the grace period', 'Payment timeliness over the last 24 months is on file'],
      any: ['{nsf} or more NSF events in the last {months} months', 'A payment arrangement that broke', '{reminders} or more reminders sent with no response'] },
    { id: 'credit-request', group: 'Billing', name: 'Credit request outside the normal pattern', result: 'Found 7 matching credit requests',
      seg: ['A credit requested on a tenant account is over', { p: 'amount', w: '96px' }, 'for its reason code, or has no supporting document attached'],
      params: { amount: '$250.00' },
      checks: ['Credit request is pending approval on a resident ledger', 'Reason code matches the ledger activity it references', 'Excludes credits inside an approved concession schedule'],
      any: ['Amount is over {amount} for the selected reason code', 'No concession, refund, or work-order document is attached'] },
    { id: 'bill-pattern', group: 'Accounts payable', name: 'Invoice out of pattern for the vendor', result: 'Found 5 matching invoices',
      seg: ['An AP invoice differs from its purchase order, or from the vendor’s last approved invoice, by more than', { p: 'amount', w: '96px' }],
      params: { amount: '$250.00' },
      checks: ['Invoice is unposted and awaiting approval', 'Excludes invoices flagged as one-time capital work'],
      any: ['Amount differs from its purchase order by more than {amount}', 'Amount differs from the vendor’s last approved invoice by more than {amount}'] },
    { id: 'prospect-cold', group: 'Leasing', name: 'Prospect going cold', result: 'Found 23 matching prospects',
      seg: ['A prospect has had no contact for', { p: 'days', w: '64px' }, 'days, is not marked lost, and has not toured'],
      params: { days: '3' },
      checks: ['Prospect stage is Inquiry, Contacted, or Tour Scheduled', 'Prospect is not marked lost or leased', 'No logged contact in the last {days} days'],
      any: ['A unit matching their stated need is available', 'A comparable unit comes available within 30 days'] },
    { id: 'late-fee-missing', group: 'Billing', name: 'Balance past grace with no late fee posted', result: 'Found 6 matching leases',
      seg: ['A balance is past the grace period by more than', { p: 'days', w: '56px' }, 'days and no late fee has been posted for the period'],
      params: { days: '3' },
      checks: ['Balance is past the grace period by more than {days} days', 'No late fee charge exists for the current period', 'Lease is active and not on a payment arrangement', 'Excludes leases with late fees waived by a person'] },
    { id: 'rent-vs-market', group: 'Billing', name: 'Recurring rent below market rent', result: 'Found 8 matching leases',
      seg: ['A lease’s recurring rent is more than', { p: 'amount', w: '96px' }, 'below the unit’s current market rent'],
      params: { amount: '$100.00' },
      checks: ['Lease is active with an active recurring rent charge', 'Unit has a current market rent on record', 'Recurring rent is more than {amount} below market rent', 'Excludes leases inside a rent-controlled or subsidized program'] },
    { id: 'missing-resident-data', group: 'Resident data', name: 'Resident record missing contact data', result: 'Found 12 matching residents',
      seg: ['An active resident is missing a phone number, an email address, or an emergency contact'], params: {},
      checks: ['Lease status is active', 'Excludes residents who declined contact in writing'],
      any: ['No valid mobile or home phone on the primary resident', 'No email address on the primary resident', 'No emergency contact recorded on the lease'] },
    { id: 'unusual-credits', group: 'Audit', name: 'Credit outside the normal pattern', result: 'Found 4 matching credits',
      seg: ['A credit posted to a resident ledger is more than', { p: 'amount', w: '96px' }, 'above the typical credit for that property'],
      params: { amount: '$250.00' },
      checks: ['Credit posted in the last 30 days', 'Amount is more than {amount} above the property’s typical credit', 'No matching concession, refund, or approval record', 'Excludes credits entered by the controller'] },
    { id: 'unusual-deletes', group: 'Audit', name: 'Unusual number of deleted records', result: 'Found 3 matching users',
      seg: ['A user deleted more than', { p: 'count', w: '56px' }, 'records of one type within', { p: 'hours', w: '56px' }, 'hours'],
      params: { count: '10', hours: '24' },
      checks: ['Deletions recorded in the audit trail in the last {hours} hours', 'More than {count} deletions of a single record type by one user', 'Excludes scheduled purge and archive jobs', 'Excludes users with the Data Administrator role'] },
    { id: 'wo-sla', group: 'Maintenance', name: 'Work order past SLA with no update', result: 'Found 2 matching records',
      seg: ['A work order is past its SLA by more than', { p: 'hours', w: '56px' }, 'hours with no status update'],
      params: { hours: '24' },
      checks: ['Work order is open', 'SLA target has passed by more than {hours} hours', 'No status update since the SLA breach'] }
  ];

  SA.templates = [
    { id: 't-movein', name: 'Move-In Charge Integrity', cat: 'Billing', type: 'Data health', mode: 'builder', opens: 'movein', det: 'movein-charges',
      desc: 'Catches new residents who are not being billed, before a month of rent goes missing.',
      then: 'Create task → Property Manager · Flag lease · Notify Regional', shape: '7 nodes · 3 actions' },
    { id: 't-latefeegap', name: 'Uncharged Late Fees', cat: 'Billing', type: 'Data health', mode: 'quick', det: 'late-fee-missing',
      desc: 'Finds balances past grace where no late fee was ever posted.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-marketrent', name: 'Rent vs Market Rent', cat: 'Billing', type: 'Data health', mode: 'quick', det: 'rent-vs-market',
      desc: 'Surfaces leases sitting below market rent in time to act at renewal.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-residentdata', name: 'Missing Resident Data', cat: 'Resident data', type: 'Data health', mode: 'quick', det: 'missing-resident-data',
      desc: 'Finds active residents with no phone, no email, or no emergency contact.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-credits', name: 'Unusual Credits', cat: 'Audit', type: 'Data health', mode: 'builder', opens: 'credits', det: 'unusual-credits',
      desc: 'Catches credits far outside the property pattern with no approval behind them.',
      then: 'Write finding · Task → Controller · Flag the ledger', shape: '7 nodes · 3 actions' },
    { id: 't-deletes', name: 'Unusual Deletes', cat: 'Audit', type: 'Data health', mode: 'builder', opens: 'deletes', det: 'unusual-deletes',
      desc: 'Watches the audit trail for one user deleting an unusual volume of records.',
      then: 'Write finding · Notify Compliance · Task → Admin', shape: '7 nodes · 3 actions' },
    { id: 't-rentmismatch', name: 'Rent Charge Mismatch', cat: 'Billing', type: 'Data health', mode: 'quick', det: 'rent-mismatch',
      desc: 'Finds recurring charges that drifted away from the signed lease rent.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-concession', name: 'Concession Cleanup', cat: 'Billing', type: 'Data health', mode: 'quick', det: 'concession',
      desc: 'Finds concessions still running with no end date on the lease.',
      then: 'Flag the record', shape: 'One sentence' },
    { id: 't-leaseexp', name: 'Lease Expiration Watch', cat: 'Leasing', type: 'Workflow', mode: 'quick', det: 'lease-exp',
      desc: 'Tells the property manager about expirations with no renewal activity, while there is still time.',
      then: 'Notify a person or role', shape: 'One sentence' },
    { id: 't-prospect', name: 'Prospect Follow-Up', cat: 'Leasing', type: 'Workflow', mode: 'builder', opens: 'prospect', det: 'prospect-cold',
      desc: 'Keeps live prospects in contact until they tour, lease, or say no — without over-messaging.',
      then: 'Follow-up template · Tour offer · Task → Leasing Agent · Mark cold', shape: '8 nodes · 4 actions' },
    { id: 't-ntv', name: 'Move-Out Inspection Watch', cat: 'Leasing', type: 'Data health', mode: 'quick', det: 'ntv-inspection',
      desc: 'Finds notices to vacate with no inspection scheduled before the move-out date.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-credit', name: 'Credit Approval', cat: 'Billing', type: 'Workflow', mode: 'builder', opens: 'credit', det: 'credit-request',
      desc: 'Clears small, documented credits on resident ledgers and routes the rest to a person who can approve them.',
      then: 'Approve within limit · Send for approval · Request documentation · Decline', shape: '12 nodes · 4 actions' },
    { id: 't-w9', name: 'Vendor W-9 Compliance', cat: 'Accounts payable', type: 'Data health', mode: 'quick', det: 'w9',
      desc: 'Finds vendors past the 1099 threshold with no W-9 on file, before year end.',
      then: 'Create a task', shape: 'One sentence' },
    { id: 't-bill', name: 'Bill Approval Assist', cat: 'Accounts payable', type: 'Workflow', mode: 'builder', opens: 'bill', det: 'bill-pattern',
      desc: 'Moves clean invoices toward payment and stops the ones that do not match their paperwork.',
      then: 'Approve · Send for approval · Hold for PO or W-9 · Task → AP', shape: '8 nodes · 4 actions' },
    { id: 't-dupvendor', name: 'Duplicate Vendor Check', cat: 'Accounts payable', type: 'Data health', mode: 'quick', det: 'dup-vendor',
      desc: 'Finds vendor records that share a tax ID, bank account, or remit-to address.',
      then: 'Create a task', shape: 'One sentence' },
    /* RECONSTRUCTED — this entry was truncated in both design files.
       Rebuilt from detLibrary['reminder-futility'] and the oversight copy on
       the AR + notification editors, which both name "Delinquency Follow-Up". */
    { id: 't-delinq', name: 'Delinquency Follow-Up', cat: 'Collections', type: 'Workflow', mode: 'builder', opens: 'delinq', det: 'reminder-futility',
      desc: 'Stops sending written reminders to residents whose history says another letter will not produce a payment, and escalates them to a person instead.',
      then: 'Hold the reminder · Task → Regional Manager · Offer an arrangement · Escalate', shape: '9 nodes · 4 actions' }
  ];
})(window.SA = window.SA || {});
